language: ruby

sudo: false

fast_finish: true

script: bundle exec rspec

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  bundler: true
