language: ruby
sudo: false

fast_finish: true
script: rake $RUN

before_install:
  # thanks to https://mediocre.com/forum/topics/phantomjs-2-and-travis-ci-we-beat-our-heads-against-a-wall-so-you-dont-have-to
  - "mkdir -p phantom20"
  - "export PATH=`pwd`/phantom20:$PATH"
  - "echo $PATH"
  - "pushd phantom20"
  - "ls phantomjs || curl -L -O https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "ls phantomjs || tar xjvf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "rm -rf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "popd"
  # Keep track of which version of phantomjs we're running the specs against
  - phantomjs -v

matrix:
  include:
    - rvm: 2.4.0
      env: OPAL_VERSION='master'
    - rvm: 2.3.3
      env: OPAL_VERSION='~> 0.10.3'
    - rvm: 2.2.4
      env: OPAL_VERSION='~> 0.9.4'
    - rvm: 2.1.10
      env: RACK_VERSION='< 2.0'
    - rvm: 2.0.0
      env: RACK_VERSION='< 2.0'

    # We use 2.1.9 to differentiate the rvm version
    # as travis doesn't allow failures by env.
    - rvm: 2.1.9
      env: RUN=zepto PATH=".:$PATH" RACK_VERSION='< 2.0'

  allow_failures:
    - rvm: 2.1.9

